### PR TITLE
Re wh smp 66 website landing page

### PR DESCRIPTION
**Pull request by idongessien**

### CODE REVIEW

**Review by melissacela — APPROVED** [review]
We have to resolve merge conflicts

**Review by Noble-Webb — CHANGES_REQUESTED** [review]
Please add a paragraph amount of text to the abstract to check it’s dynamic ability. Client specifically asked for this. (Not a joke Scott actually requested for that test.) I will approve after that test.

**Comment by idongessien** [comment]
> We have to resolve merge conflicts

Resolved

**Comment by idongessien** [comment]
> Please add a paragraph amount of text to the abstract to check it’s dynamic ability. Client specifically asked for this. (Not a joke Scott actually requested for that test.) I will approve after that test.

Working on this now

**Pull request merged**
